### ISSUE TITLE
API method "token-tx" returns random txid for valid tx

### ISSUE THREAD

**Issue by ilzheev** [AccumulateNetwork/accumulated#147]
Token tx API returns confusing data in response.

**Branch:** AC-423

**How to replicate the issue:**

1) Generate anonymous token account
```
go run cmd/cli/main.go account generate
```
> acc://a472a2ea0aef9f0f43b51e1096f01170a234684bfe7d77a6/ACME

2) Use faucet to get ACME tokens
```
go run cmd/cli/main.go faucet a472a2ea0aef9f0f43b51e1096f01170a234684bfe7d77a6/ACME
```

```json
{"data":{"codespace":"","hash":"4B74A1F981A19BBEDBE36AEDEC3B08DF6468744EEEC9CFD531A8356CF8C0BC82","txid":"11313597084ef402a0805d3a2993c1762cd59dc5e45533251f49ee34265b2a1b"},"type":"faucet"}
```

> 11313597084ef402a0805d3a2993c1762cd59dc5e45533251f49ee34265b2a1b

3) Get `token-tx` by txid

API request:
```json
{
    "jsonrpc":"2.0",
    "id"     :1,
    "method" :"token-tx",
    "params": {
        "hash": "11313597084ef402a0805d3a2993c1762cd59dc5e45533251f49ee34265b2a1b"
    }
}
```

API response:
```json
{
    "jsonrpc": "2.0",
    "result": {
        "type": "syntheticTokenDeposit",
        "data": {
            "txid": "f40b4c5241c68cafc72d75eadd9c97ee34720f9ed199e8cbe5d669bcea597587",
            "from": "acc://03eba8d792376c77a3cd872cc93d617f100d1c615cd8def5/ACME",
            "to": "acc://a472a2ea0aef9f0f43b51e1096f01170a234684bfe7d77a6/ACME",
            "amount": "1000000000",
            "tokenURL": "acc://ACME"
        }
    },
    "id": 1
}
```

`response->result->data->txid` is `f40b4c5241c68cafc72d75eadd9c97ee34720f9ed199e8cbe5d669bcea597587` while user expects to get `11313597084ef402a0805d3a2993c1762cd59dc5e45533251f49ee34265b2a1b`

**Comment by firelizzard18** [comment]
There are two different values here, both of which are hashes, both of which may be referred to as a transaction ID. One is the hash that Accumulate uses, which is calculated from the payload and signature info. The other is the hash that Tendermint uses, which is calculated from the entire transaction as it is submitted to `broadcast_tx`.

**Comment by bunfield** [comment]
also doing a query on the source txid of a faucet transaction uses a fake txid.  To avoid confusion, i will zero out the source txid since it doesn't really exist in the protocol.

**Comment by firelizzard18** [comment]
Faucet transactions now use real txids, and everything works if you use the Accumulate transaction ID and not the Tendermint transaction hash.
